### ISSUE TITLE
Great idea, unfortunately relies on non-free services to function

### ISSUE THREAD

**Issue by desrod** [cudeso/ulogd-viz#1]
I finally took some time to get this configured and working today, but ran into quite a few blockers: 

- It relies on Google Maps API, which is a billed service, non-free. 
- It relies on the MaxMind database of cities, which is also encumbered by account requirements
- The various php files in the root of www and the config/ subdirectory are hard-coded with PHP paths that have to be edited in order to bring up the UI, and many require_once() directives have to be copied to load them into the compiler namespace. 
- I had to touch nearly every file to remove the hard-coded path to '../config/ulogd.php' and get the data files in 'library' seen and loaded with separate directives. 

But the biggest blocker for me, was I can't use the mapping API without being charged for it. Loading the maps page gives you an error that specifically says you need to enable billing on your developer account with Google for use of that API. 

It looks like this project may have been abandoned, so I'm just leaving this here for anyone else who runs across this and wants to run this on their own infra.

**Comment by lucidprojects** [comment]
Thanks desrod.  

Just happened upon this myself would be nice if it just worked.  your comment probably saved me a few hours of hacking...

I guess you could just use grafana once you have the data in a db.  

Looks like there is a plugin for mapping https://grafana.com/grafana/plugins/grafana-worldmap-panel but you would need long and lat data...

But again more hacking...
